### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by sindresorhus** [darcyclarke/ama#10]

**Comment by darcyclarke** [comment]
This is a hard question as I find new favorite projects all the time. That said, I'm still really into @alex's [What Happens When](https://github.com/alex/what-happens-when) repo. There's a lot of that goes into a single web page request/load and it's interesting to see the whole process laid out. I think it's definitely one of the best resources for any web developer no matter what their skill level or experience is. It's a simple premise with a huge payoff.
