### ISSUE TITLE
What drives you? 

### ISSUE THREAD

**Issue by LindseyB** [darcyclarke/ama#17]

**Comment by darcyclarke** [comment]
Hey @LindseyB! I apologize for the EXTREMELY delayed response here. 

That said, I think there's always been a number of factors at work that "drive" me. When I first started to program I was in my early teens; the ability to express myself in a new way was what really drove my exploration into tech/web. I have a background in art and so I looked at writing code as if it were a new medium (ie. a new paint brush and canvas). 

Since then, I think I've been driven to share my knowledge and experiences. I haven't really wavered in my career trajectory since I was about 16; so it means I've had a pretty good focus on the web ecosystem and have been able to watch the technology and community change and mature over a long period of time. Sharing what I know, for free, gives me a lot of satisfaction.
