### ISSUE TITLE
What are your thoughts on the inline CSS discussion that's surrounding components like React? 

### ISSUE THREAD

**Issue by drewminns** [darcyclarke/ama#5]
http://projects.formidablelabs.com/radium/

**Comment by darcyclarke** [comment]
So... I've got mixed feelings really. I do think there's a shake-up happening with the CSS community right now. Preprocessors are probably going to go the way of the dodo and you're going to see styles written as JavaScript objects (look into [JSS](https://github.com/jsstyles/jss)). I'll personally be writing my styles in CoffeeScript 'cause semicolons, curly braces and commas are the devil (`.styl` < `.coffee`). I'm actually doing a talk on this at [jQuery Conf India](http://confengine.com/jquery-conf-2015/proposal/1199/workshop-revolutionizing-your-css), read the outline to get a sense of the content. 

As far as inline styles go, I don't like the implementation and have a hard time seeing the value. As far as I know **inline style attributes and inline style tags both cause reflows**. I can't imagine this being overly performant when you have a number of elements all with individual style attributes defined. It also dirties your markup (have fun navigating the elements panel in dev tools o_O). The way it's being implemented in Radium also seems dangerous from a versatility standpoint. You're essentially getting locked into a single framework for all your HTML, JS & CSS. I can't imagine how bad you'd want inline styles to give up flexibility and interoperability with other non-React projects. 

**Essentially**, I think they've got a lot of the tech right but the implementation wrong.

**Some relevant history**: back in 2013, Nick Fisher (@spadgos) actually did a talk about how SoundCloud was turning their styles into modular components that they could require and inject, inline, whenever that corresponding view was included/rendered. That technique peaked my interest at the time but still wasn't ideal. What they generated looked something like the below:

``` html
<div class="my-view">
  <style>...</style>
  ...
  <div class="my-other-view">
    <style>...</style>
    ...
  </div>
</div>
```

Spec-wise, we got close to a similar native solution with the [`scoped` attribute](https://html.spec.whatwg.org/multipage/semantics.html#attr-style-scoped) for the `style` tag. Unfortunately, Firefox is the only browser to implement it fully while Chrome has kept support behind an experimental flag ([see more support dets](https://html.spec.whatwg.org/multipage/semantics.html#attr-style-scoped)). Of course, this still creates markup that looks like the above (which, as I said, isn't ideal). 

I appreciate the idea of trying to keep everything modular and associating styles with their view but I think it's just as easy to create an overarching view folder (containing scripts/styles) or name your styles and scripts files respectively. Style encapsulation isn't that big of a deal anymore since the [`all` property](https://developer.mozilla.org/en-US/docs/Web/CSS/all) came out. This is also partly why I think the Web Components spec is kind of useless _but I digress_.

> _If you're having specificity issues I feel bad for you son, I got 99 problems and selectors ain't one_

**My suggestion for writing & shipping CSS:**
- Write your styles in JavaScript (CSS is dead :P check out [JSS](https://github.com/jsstyles/jss) or [PostCSS](https://github.com/postcss/postcss))
- Create corresponding views files for both scripts and styles (ie. `/src/scripts/MyView.js` and `/src/styles/MyView.js`) 
- Define the styles that are necessary for initial page load in some kind of base file (ie. `/src/styles/base.js`)
- Create a build process to generate and inject your base styles in the head of the document (ie. [gulp-inject](https://www.npmjs.com/package/gulp-inject))
- Create a build process to generate the rest of your app styles and load with [loadCSS](https://github.com/filamentgroup/loadCSS)

**Key Takeaways:**
- JavaScript styles: yes
- Modular styles: yes
- Inline styles: no

_Note: I'll probably write a blog post about this and go into more depth soon after returning from India & New York (ie. early-August)_

**Comment by spadgos** [comment]
Hey Darcy, thanks for the mention here. To give an update on what we're doing for styles at SoundCloud, late last year we switched to using [Webpack](https://github.com/webpack/webpack) and use their [CSS loader](https://github.com/webpack/css-loader). The way that works is surprisingly similar to what we came up with a few years earlier, however the CSS is injected to the page in one hit, rather than as required by each view.
